users:
    admin: "password"
    root: "root"

database:
    name: "test.db"

plugins:
    SenseHAT: true
    alert: 
        enable: true
        type:
            motion_detected: 
                file: "alert.mp3"
                times: -1
            temperature: 
                file: "notification.mp3"
                times: 1
            humidity: 
                file: "notification.mp3"
                times: 1
            pressure: 
                file: "notification.mp3"
                times: 1

# Below are temporary settings
threshold:
    temperature: 
        upper: 30
        lower: 20
    humidity: 
        upper: 70
        lower: 20
    pressure: 
        upper: 1200
        lower: 800

email: "ui@shigure.ch"